name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v8

      - name: Build with Gradle
        run: ./gradlew build
#
#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v8
#        with:
#          name: Package
#          path: build/libs